---

- name: instalando puppet-agent com todas as maquinas
  package:
   name: puppet-agent
   update_cache: yes
   state: present

- name: dando start no puppet qando for redhat
  service:
   name: puppet 
   state: restarted
  when: ansible_os_family == "RedHat"
