- name: instalando o docker na maquina docker
  hosts: docker
  tasks:
    - nome: instalando o docker
      shell: |
       curl -fsSL https://get.docker.com -o get-docker.sh
       sudo sh get-docker.sh
