---
- name: instalando pacotes
  hosts: all
  tasks:
  - name: instalando no Debian
    package:
     name: 
      - apache2
      - vim
      - htop
      - cowsay
      - figlet
     state: present
    when: ansible_os_family == "Debian"

  - name: instalando no Redhat
    package:
     name: 
      - httpd
      - epel-release
      - htop
      - vim
      - cowsay
      - figlet
     state: present
    when: ansible_os_family == "redhat"

