---

- name: adicionando pacotes
  hosts: all
  tasks:
#   - name: instalando o vim
#     package:
#      name: 
#       - vim
#       - htop
#      state: present
   - name: enviando um arquivo
     copy: 
      src: /etc/hosts
      dest: /etc/hosts     
   - name: garantindo uma nova linha no etchosts
     lineinfile:
      dest: /etc/hosts
      line: '192.168.200.1 desktop'
   - name: garantindo um bloco de configuracao
     blockinfile:
      dest: /etc/hosts
      block: | 
       192.168.0.10 desktop1
       91.2168.0.11 desktop2
